server:
    port: ${port:8888}
spring:
    application:
        name: sankar-spring-cloud-config-server
    cloud:
        config:
            enabled: true
            server:
                git:
                    default-label: main
                    uri: https://github.com/sanknara/environment-variables.git
